version: "2"
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
              enabled: false
  exclude_paths:
  - "src/main/resources/cssify.js"