plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
engines:
  checkstyle:
    enabled: true
    checks:
      com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck:
              enabled: false